GET http://localhost:3000/getUser HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImVtYWlsIjoiY3VzdG9tZXJAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzMwMTA4ODc0LCJleHAiOjE3MzAxMDkwNTR9.cpSd5Htci0h6VuVHoZs0_tYQQD7QnFuD8crJ7Cr6XWM