POST http://localhost:3000/auth/sign-up HTTP/1.1
Content-Type: application/json

{
  "firstName":"customer",
  "lastName":"customer",
  "displayName":"customer",
  "password":"customer@gmail.com",
  "email":"customer@gmail.com",
  "role":"customer"
}